name: flights-analysis
dependencies:
- appnope=0.1.0=py27_0
- basemap=1.0.7=np110py27_0
- certifi=14.05.14=py27_0
- decorator=4.0.4=py27_0
- freetype=2.5.2=2
- geos=3.3.3=0
- ipykernel=4.1.0=py27_0
- ipython=4.0.0=py27_1
- ipython-notebook=4.0.4=py27_0
- ipython_genutils=0.1.0=py27_0
- jinja2=2.8=py27_0
- jsonschema=2.4.0=py27_0
- jupyter_client=4.1.1=py27_0
- jupyter_core=4.0.6=py27_0
- libpng=1.6.17=0
- libsodium=0.4.5=0
- markupsafe=0.23=py27_0
- matplotlib=1.4.3=np110py27_3
- mistune=0.7.1=py27_0
- nbconvert=4.0.0=py27_0
- nbformat=4.0.1=py27_0
- notebook=4.0.6=py27_0
- numpy=1.10.1=py27_0
- openssl=1.0.1k=1
- pandas=0.17.0=np110py27_0
- path.py=8.1.2=py27_0
- pexpect=3.3=py27_0
- pickleshare=0.5=py27_0
- pip=7.1.2=py27_0
- ptyprocess=0.4=py27_0
- pygments=2.0.2=py27_0
- pyparsing=2.0.3=py27_0
- pyqt=4.11.4=py27_0
- python=2.7.10=1
- python-dateutil=2.4.2=py27_0
- python.app=1.2=py27_4
- pytz=2015.6=py27_0
- pyzmq=14.7.0=py27_0
- qt=4.8.7=1
- readline=6.2=2
- setuptools=18.4=py27_0
- simplegeneric=0.8.1=py27_0
- sip=4.16.9=py27_0
- six=1.10.0=py27_0
- sqlite=3.8.4.1=1
- ssl_match_hostname=3.4.0.2=py27_0
- terminado=0.5=py27_0
- tk=8.5.18=0
- tornado=4.2.1=py27_0
- traitlets=4.0.0=py27_0
- wheel=0.26.0=py27_1
- zeromq=4.0.5=0
- zlib=1.2.8=0
- pip:
  - aggdraw-1.1==64bits
  - backports.ssl-match-hostname==3.4.0.2
  - gcmap==0.0.3
  - ipython-genutils==0.1.0
  - jupyter-client==4.1.1
  - jupyter-core==4.0.6
  - pillow==2.7.0
  - pyproj==1.9.4

